### ISSUE TITLE
Login window not scaling well with other font sizes

### ISSUE THREAD

**Issue by philippeback** [JurajKubelka/DiscordSt#3]
![image](https://user-images.githubusercontent.com/2128441/33344196-6bcf842c-d488-11e7-9174-224240ac58c0.png)

See pic

**Comment by JurajKubelka** [comment]
Hi @philippeback. Thanks for the report. Do you have an idea how to fix it? Check the following example: 

```Smalltalk
| model |
model := DynamicComposableModel new
	assign: TextInputFieldModel new to: #emailInput;
	layout: (SpecColumnLayout composed
		newRow: [ :row | row add: #emailInput ] 
			height: ComposableModel inputTextHeight;
		newRow: [ :row | ];
		yourself).
model openWithSpec.
```

I do not see any option to force `TextInputFieldModel` to use another font size. Is it a Spec issue or do I miss an API?

**Comment by JurajKubelka** [comment]
Executing `TextInputFieldModel example` is even more simple example with the same issue.

**Comment by JurajKubelka** [comment]
```Smalltalk
"Does not work"
TextInputFieldModel example.

"Does not work"
PluggableTextFieldMorph new
	on: ZnStringEntity new 
	text: #string 
	accept: #string: 
	readSelection: nil 
	menu: nil;
	openInWindow.	

"Work"
TextMorphForFieldView new
	newContents: 'Hello Pharo';
	openInWindow.
```

**Comment by JurajKubelka** [comment]
The strange behavior:

```Smalltalk
PluggableTextFieldMorph >> #beDecrypted

	self textMorph font: TextStyle defaultFont.
```

And the issue is that `TextStyle defaultFont textStyle` return a small font.

**Comment by JurajKubelka** [comment]
Reported on Pharo project: https://pharo.fogbugz.com/f/cases/20789/

**Comment by JurajKubelka** [comment]
The UI will be replaced by a new widget.
