### ISSUE TITLE
Cannot send message to Message group

### ISSUE THREAD

**Issue by jecisc** [JurajKubelka/DiscordSt#44]
Pharo version: 6.1

When I try to select someone to send a direct message I get this error:

Instance of DSDirectMessageGroupChannel did not understand #position

DSDirectMessageGroupChannel(Object)>>doesNotUnderstand: #position
[ :a :b | a position < b position ] in DSSortChannelsCommand>>rootChannels in Block: [ :a :b | a position < b position ]
Array(SequenceableCollection)>>mergeFirst:middle:last:into:by:
Array(SequenceableCollection)>>mergeSortFrom:to:src:dst:by:
Array(SequenceableCollection)>>mergeSortFrom:to:src:dst:by:
Array(SequenceableCollection)>>mergeSortFrom:to:src:dst:by:
Array(SequenceableCollection)>>mergeSortFrom:to:src:dst:by:
Array(SequenceableCollection)>>mergeSortFrom:to:src:dst:by:
Array(SequenceableCollection)>>mergeSortFrom:to:src:dst:by:
DSChannels(OrderedCollection)>>sort:
DSSortChannelsCommand>>rootChannels
DSSortChannelsCommand>>execute
[ :jsonReader | 
| specifiedChannels |
specifiedChannels := jsonReader nextAs: #CollectionOfSpecifiedChannels.
DSSortChannelsCommand new
	channels: specifiedChannels;
	execute;
	sortedChannels ] in [ :mapping | 
mapping
	reader: [ :jsonReader | 
		| specifiedChannels |
		specifiedChannels := jsonReader
			nextAs: #CollectionOfSpecifiedChannels.
		DSSortChannelsCommand new
			channels: specifiedChannels;
			execute;
			sortedChannels ].
mapping
	writer: [ :jsonWriter :aCollection | 
		| flattenedChannels |
		flattenedChannels := DSFlattenChannelsOrderByIdCommand new
			channels: aCollection;
			execute;
			flattenedChannels.
		jsonWriter nextPut: flattenedChannels ] ] in DSModelJsonMapping class>>collectionOfSortedChannelsMappingFor: in Block: [ :jsonReader | ...
NeoJSONCustomMapping>>readFrom:
NeoJSONReader>>nextAs:
DSModelJsonMapping class>>read:withMapping:on:
DSRestApiSix>>directChannels
DSClient(DSAbstractClient)>>directChannels
DSClientRegistry>>directChannels
DSDirectMessageItem>>textChannels
ByteSymbol(Symbol)>>cull:
DSDirectMessageItem(ProtoObject)>>ifNotNil:ifNil:
DSClientRegistry>>channelsOfSelectedServer
DSServerChannelListMorph>>channels
DropListMorph>>updateList
DropListMorph>>update:
MorphChanged>>deliverTo:
DropListMorph(Morph)>>handleUpdate:
MessageSend>>value:

**Comment by jecisc** [comment]
I installed it today with this script: 

```
Metacello new
    baseline: #DiscordSt;
    repository: 'github://JurajKubelka/DiscordSt/src';
    load: #('light')
```

**Comment by JurajKubelka** [comment]
Wow! A merge did not work properly because it was fixed last week #30.

**Comment by JurajKubelka** [comment]
@jecisc: I believe that you do not use updated version. Do you use Iceberg? If so, then the `Metacello` does not update the repository correctly. It uses an existing one you installed last week. I remember that you reported it last Monday and we tested together, right?

**Comment by jecisc** [comment]
I was not sure it was exactly the same error :) 

I'll try to check if Iceberg still load another version later. Now I'm a little short on time. I opened the issue to not forget the problem.

**Comment by JurajKubelka** [comment]
Thanks! And let me know :-)

**Comment by jecisc** [comment]
Deleting my cache worked.
