### ISSUE TITLE
Not loading into gtoolkit

### ISSUE THREAD

**Issue by markfirmware** [JurajKubelka/DiscordSt#77]
![Screenshot from 2021-02-25 18-10-00](https://user-images.githubusercontent.com/22677068/109231522-c7730080-7794-11eb-91a0-d988fe6efe0a.png)

I do not know the pharo version inside of gtoolkit. I cannot find a version report in its monitor.

**Comment by JurajKubelka** [comment]
Hi @markfirmware, thank you for the report. Please, try to use `onConflictUseLoaded` method:

```Smalltalk
Metacello new
    baseline: #DiscordSt;
    repository: 'github://JurajKubelka/DiscordSt/src';
    onConflictUseLoaded;
    load.
```
